### ISSUE TITLE
unsorted unfiltered review

### ISSUE THREAD

**Issue by amir-arad** [CommaSword/noise-generator#6]
- module API is an exported function. consider going more [es6-modules](http://exploringjs.com/es6/ch_modules.html#sec_basics-of-es6-modules) friendly with named exports
 - using Proxy is an overkill (harder to debug, to mock, misleading: async API posing as sync API,  hidden serialization boundaries etc.). If going for an extendable Audio proxy, consider using named getters and setters,  and allow explicit extension. 
 - if still bound on supplying magical proxy, consider using [comlink](https://github.com/GoogleChromeLabs/comlink) over the json stream.
 - keeping the state in `audios` is avoidable, and it makes the module itself stateful. consider using the closure of the `Audio` function to hold the state.
 - dunnow about `readFileSync` on the electron side. on one hand it's inefficient, on the other hand it keeps the code simpler. I'd go for async - await and support reading files simultaniously.

**Comment by amir-arad** [comment]
also, readme is misleading! out of date, or ahead of it's time?

**Comment by imsnif** [comment]
Thanks for your input! I have some comments and will leave this issue open until we agree on everything. Once we do, I'll bulk fix everything then close it.

1. Right. For a single exported function I usually prefer not to beat around the bush, but I don't mind making it a named export.
2. using Proxy: so, I'm indeed trying to replicate the HTML Audio Element API in a transparent way (as much as possible). That's the reason for the Proxy. The Audio API is the misleading one in regards to async/sync behaviour (eg. volume changing, loop, mute, etc.) . :) 
I didn't want to use explicit named getters and setters because I don't want to have to own all of those features and write all that boilerplate. This will be a problem though in future features (eg. `get readyState` `get seekable` etc.) which will have to use Promises even though the original API does not. These will override the Proxy methods and implement Promises unless I find a better solution (would love to hear suggestions!). But that's for the future when this module is broken out.
3. That's a really cool module and if I'm convinced to have everything async (see point 2) I'll definitely go for it, thanks!
4. The module is stateful because it has (and must have) just one `electron` instance. I don't see a way around it. I had some thoughts of refactoring the `audios` hashmap elsewhere (most of this module will go through extensive refactoring once the issues are dealt with). I now see that placing it in the `Audio` function will definitely be a good call! I think I didn't do it earlier because I had some other functionality that was simplified away. Thanks!
5. I haven't measured performance, but how many files would I have to load for the performance impact to be significant? Wouldn't I reach some other hardware/driver/whatever cap before that? (I'm honestly asking - we can measure this of course if you're also unsure).

Thanks again for the feedback.

**Comment by amir-arad** [comment]
I have bad experience with the es6-proxy-as-async-bridge approach. JS is very sensitive to sync/async differences, more than other (multithreaded) languages, and even in those ,languages this is a pitfall. 
It's a major difference in the API so I suggest either implementing it the same way (optimistic caching of remote state such as `readystate`) or expose another API which is async by nature.

I think  comlink does a very good work implementing the infrastructure for it, though.

**Comment by imsnif** [comment]
My goal with the separate module is for developers to be able to use it in order to spoon browser apps in node, hence the particularity regarding the api. I do think exposing an async version of the api has merit though. Those are definitely questions I'll answer once I break that module out.
As for this module, I can definitely have its creation and operations (volume change) return promises until that change is made, so as not to break the API when I break out the module.
So the takeaway from this feedback (please add/change/remove as you see fit before I break it to separate issues for order's sake):

1. Adjust the `Audio` api to at least have a fully async promisified version.
2. Named export of main module
3. Consider refactoring to use `comlink`
4. Avoid keeping the `audios` index as part of the module state

**Comment by amir-arad** [comment]
sounds right

if you do item 3,  it should take care of 1
